---
- hosts: tomcat1
  serial: 1
  become: yes
  become_method: sudo
  #  vars:
  #  package_name: devopsarea-1.0.war

  tasks:
   - name: Install pip
     apt: name=python-pip state=present

   - name: install docker-py package
     pip: name=docker-py

   - name: Running the container
     docker_container:
       image: tomcat:latest
       name: tomcat
       state: running

   - name: Configure Tomcat users
     copy:
       src: tomcat-users.xml
       dest: /etc/tomcat*/
       owner: root
       group: tomcat*
       mode: 0640

   - name: Stop the firewall
     service:
       name: ufw
       state: stopped

#   - name: restart tomcat
#     service:
#       name: tomcat8
#       state: restarted


#   - name: wait for tomcat to start
#     wait_for: port=8080

   - name: deploy the generated package to tomcat
     copy:
       src: ./target/devopsarea-1.0.war
       dest: /var/lib/tomcat8/webapps/
       mode: 0777                                                                                                                                                                              
